# Generated by Django 5.0.8 on 2024-08-21 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='page',
        ),
        migrations.AddField(
            model_name='copy',
            name='anunciante',
            field=models.CharField(default='Desconocido', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='category',
            field=models.ForeignKey(db_column='id_category', default='0', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category'),
        ),
        migrations.AddField(
            model_name='copy',
            name='fecha',
            field=models.DateField(default='2024-08-01'),
        ),
        migrations.AddField(
            model_name='copy',
            name='file',
            field=models.FileField(default='Sin archivo', upload_to='files/'),
        ),
        migrations.AddField(
            model_name='copy',
            name='hora',
            field=models.TimeField(default='0'),
        ),
        migrations.AddField(
            model_name='copy',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='medio',
            field=models.CharField(default='Sin medio', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='processing',
            field=models.BooleanField(default='No'),
        ),
        migrations.AddField(
            model_name='copy',
            name='producto',
            field=models.CharField(default='Sin producto', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='programa',
            field=models.CharField(default='Sin programa', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='tema',
            field=models.CharField(default='Sin tema', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='vehiculo',
            field=models.CharField(default='Sin vehiculo', max_length=255),
        ),
        migrations.AddField(
            model_name='copy',
            name='version',
            field=models.CharField(default='Sin versión', max_length=255),
        ),
    ]
