# Generated by Django 5.0.8 on 2024-08-21 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_copy_content_remove_copy_page_copy_anunciante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category'),
        ),
    ]
