# Generated by Django 5.0.8 on 2024-08-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='category',
            field=models.ForeignKey(db_column='category_id', default='0', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category'),
        ),
    ]
